### ISSUE TITLE
how to use this code with DICOM format ? 

### ISSUE THREAD

**Issue by Najat91** [perone/medicaltorch#18]

**Comment by perone** [comment]
HI @Najat91, we don't support DICOM and we probably not will be supporting it in the future because it is not an efficient data format and most tools do not support it. Most tools are in favor of using NIfTI files and this is the format that we support. 
There are many tools you can use to convert DICOM to NIfTI, one of them is `dcm2nii`, that you can find [here](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage). There is also a [tutorial from FSL here](https://www.youtube.com/watch?v=rv8pAIaRS9Q).

**Comment by Najat91** [comment]
i understand, i convert my data to nii , but the problem is my ground truth is txt file, how to do in this case?

**Comment by udion** [comment]
You can write your own pytorch dataloader. I find this tutorial awesome
https://stanford.edu/~shervine/blog/pytorch-how-to-generate-data-parallel
